"""remove unique constraint on phone number

Revision ID: 06da54b488f9
Revises: 
Create Date: 2025-07-28 05:53:59.426065

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06da54b488f9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sms_queue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('registration_time', sa.DateTime(), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.CheckConstraint('duration <= 60', name='duration_max_60_minutes_check'),
    sa.CheckConstraint('duration > 0', name='duration_positive_check'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_type', 'position', name='uq_event_type_position'),
    sa.UniqueConstraint('phone_number', 'event_type', name='uq_phone_number_event_type')
    )
    with op.batch_alter_table('sms_queue', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sms_queue_phone_number'), ['phone_number'], unique=False)

    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    with op.batch_alter_table('sms_queue', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sms_queue_phone_number'))

    op.drop_table('sms_queue')
    # ### end Alembic commands ###
