"""empty message

Revision ID: 103486f08ce6
Revises: 414b922eae28
Create Date: 2025-08-01 19:17:58.081049

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '103486f08ce6'
down_revision = '414b922eae28'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sms_queue', schema=None) as batch_op:
        batch_op.add_column(sa.Column('clicked_time', sa.String(length=5), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sms_queue', schema=None) as batch_op:
        batch_op.drop_column('clicked_time')

    # ### end Alembic commands ###
