"""Added ID to queue entry

Revision ID: 1f5d7b18e692
Revises: b8ec4a16aa24
Create Date: 2025-07-31 05:23:07.795821

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f5d7b18e692'
down_revision = 'b8ec4a16aa24'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sms_queue', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sms_queue', schema=None) as batch_op:
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
