"""Added school field to user model

Revision ID: 3722ced4bf3d
Revises: 
Create Date: 2025-07-27 03:08:33.173581

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3722ced4bf3d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('queue_entry',
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('registration_time', sa.String(length=20), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('phone_number')
    )
    with op.batch_alter_table('queue_entry', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_queue_entry_phone_number'), ['phone_number'], unique=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('school', sa.String(length=100), nullable=True))
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=128),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
        batch_op.drop_column('school')

    with op.batch_alter_table('queue_entry', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_queue_entry_phone_number'))

    op.drop_table('queue_entry')
    # ### end Alembic commands ###
