"""empty message

Revision ID: 414b922eae28
Revises: c0bf79f00b92
Create Date: 2025-08-01 18:33:15.602036

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '414b922eae28'
down_revision = 'c0bf79f00b92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sms_queue', schema=None) as batch_op:
        batch_op.drop_column('time_zone')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sms_queue', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time_zone', sa.VARCHAR(length=50), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
