"""add last reminder column

Revision ID: 70b820ec232b
Revises: 06da54b488f9
Create Date: 2025-07-28 06:57:51.749219

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70b820ec232b'
down_revision = '06da54b488f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sms_queue', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_reminder_time', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sms_queue', schema=None) as batch_op:
        batch_op.drop_column('last_reminder_time')

    # ### end Alembic commands ###
