"""switched shower id to be nullable

Revision ID: b8ec4a16aa24
Revises: cd6d73ae53e4
Create Date: 2025-07-31 01:03:59.633076

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8ec4a16aa24'
down_revision = 'cd6d73ae53e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sms_queue', schema=None) as batch_op:
        batch_op.execute("UPDATE sms_queue SET shower_id = 1 WHERE shower_id IS NULL")
        batch_op.alter_column('shower_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sms_queue', schema=None) as batch_op:
        batch_op.alter_column('shower_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
