"""empty message

Revision ID: c0bf79f00b92
Revises: 1f5d7b18e692
Create Date: 2025-08-01 17:36:16.728944

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0bf79f00b92'
down_revision = '1f5d7b18e692'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sms_queue', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time_zone', sa.String(length=50), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sms_queue', schema=None) as batch_op:
        batch_op.drop_column('time_zone')

    # ### end Alembic commands ###
