"""add nullable shower_id to queue entry

Revision ID: cd6d73ae53e4
Revises: f5bb790be2d2
Create Date: 2025-07-31 01:02:30.829332

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd6d73ae53e4'
down_revision = 'f5bb790be2d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sms_queue', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shower_id', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sms_queue', schema=None) as batch_op:
        batch_op.drop_column('shower_id')

    # ### end Alembic commands ###
