"""change length of clicked time

Revision ID: ee79d45427c9
Revises: 103486f08ce6
Create Date: 2025-08-13 15:53:19.254507

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee79d45427c9'
down_revision = '103486f08ce6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sms_queue', schema=None) as batch_op:
        batch_op.alter_column('clicked_time',
               existing_type=sa.VARCHAR(length=5),
               type_=sa.String(length=20),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sms_queue', schema=None) as batch_op:
        batch_op.alter_column('clicked_time',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=5),
               existing_nullable=False)

    # ### end Alembic commands ###
